version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Frontend port
      - "8000:8000"  # Backend API port
    volumes:
      - ./frontend:/app/frontend:cached
      - ./backend:/app/backend:cached
      - ./database:/app/database:cached
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: always
