### Get all tables
GET http://localhost:8000/tables

### Get all columns kunde_Tabel
GET  http://localhost:8000/columns/Kunde_tabel

### Get all columns items_tabel
GET  http://localhost:8000/columns/Items_tabel

### Add a new table
POST http://localhost:8000/tables
Content-Type: application/json

{
    "table_name": "table_1",
    "description": "This is a test table"
}


