### Get all tables
GET http://localhost:8000/tables

### Get all columns
GET  http://localhost:8000/columns/example_table

### Add a new fruit
POST http://localhost:8000/tables
Content-Type: application/json

    {
        "table_name": "tabel 1",
        "description": "This is a test table",
    }


